### ISSUE TITLE
What event to listen on to know that client will no longer attempt to reconnet

### ISSUE THREAD

**Issue by SaikiranDaripelli** [primus/primus#274]
Hi,
   I am trying to figure out what event or flag will determine that client connection is closed and primius will no longer try to reconnect. i am using default reconnect strategy.

i tried "end" and "close" events, though "end" event is fired when all reconnect attempts are done in case of server issues and works as expected, but in case of online/offline behaviour "end" is emitted even when i go offline and primus will still reconnect when i am back online even after firing end.

All i am trying to solve is to show some error messages like , "reconnecting...." when we are trying to reconnect and "error occurred, we will not retry so please refresh the page...."

**Comment by akreienbring** [comment]
Hello,
I,ve got a very similar question, so I better reopen this one instead of posting a new issue.
My app should stay permanently connected to the primus server to be able to accept messages.

Currently I configured it for infinit reconnections uing the default strategy although I have an authorization hook in place. 
```
				reconnect: {
					maxDelay: Infinity, // Number: The max delay for a reconnect retry.
					minDelay: 500, // Number: The minimum delay before we reconnect.
					retries: 10 // Number: How many times should we attempt to reconnect.
				},
```
I'm stil reconnecting in the case of a timeout because there's the Zombie timeout on the server that kills the connection if the client is not sending data every 35 sec. 
So, if I'd remove 'timeout' from the strategie my app won't be able to receive messages, correct? Or should I disable the Zombie timeout completely AND remove the timeout strategy on the client?

Addionally I wan't to force a reconnection if the server terminates the connection for whatever reason. 

So I react on the 'close' event and call primus.end() followed by a primus.connect() as soon as my app notices that primus.readyState == Primus.CLOSED (provided the server is back online). Therfor I ended up checking for Primus.OPEN every time the client wants to send a message...

My question: Is there a better way to achieve what I want?

**Comment by akreienbring** [comment]
Is there any different behaviour when the client app is in background mode? Although I disabled zombie spark detection by setting: 
```
{ transformer: 'engine.io', timeout: false })
```
on the server side, I still see reoccurent disconnections and reconnections from the clients when the app is in the background.

**Comment by lpinca** [comment]
@akreienbring the `timeout` strategy is used to detect if the server took too long to answer a connection request. If your initial connection was successful and you are in a reconnection procedure you shouldn't care about it. Keep in mind that the `timeout` strategy is removed by default when you use an auth hook.

When the client is connected it automatically sends ping packets to the server to prevent that the connection is closed by what you call "Zombie timeout". The `timeout` options on the client and the server are not related in any way.

When the server is closed isn't closed cleanly (server reboot, power interruption, etc.) your clients should automatically reconnect.

On the client you can send messages whenever you want, if it isn't connected, the messages will be buffered and sent when the client successfully connects.

**Comment by akreienbring** [comment]
Hello,
thanks. Yes, that' what I already knew.
But, please have a look at my second post. There's something wrong, when the phone is in StandBy Mode. 
I tested with primus latest. Transformer is engine.io, on two devices (Android 4.4.4 and 4.4.2)
Here are my findings so far:

Issue: On the server the 
```
	primus.on('disconnection', function (spark) {
		// the spark that disconnected
	});
event is fired and the client is disconnected.

- It's NOT happening when the app goes to background, only in StandBy
- It's NOT happening when the phone is connected to my development PC via USB (Debugging)
- It is clearly related to the server timeout setting:
  - By default the client get's disconnected after 35 sec.
  - If I configure false or 'false' as the timeout value the client still disconnects after 35 sec.
  - If I configure 1 hour or higher values the client disconnects after about 90 sec.
- If I keep the 'timeout' as reconnection strategy the client immidiatly reconnects with a new spark
- If I disable the 'timeout' strategy the client only reconnects when I activate the app (app goes online)

I did a quick search on the net and found out that there seems to be some common issues with websockets and phones that go to sleep / standby.

But I wonder: If the browser / OS closes (whatever it shuts down) then why can primus still reconnect (if timeout strategy is configured)? And why has the server zombie spark detection timeout setting no effect on this?

**Comment by lpinca** [comment]
It could be that the underlying real-time framework (in your case Engine.IO) also has a heartbeat system to kill zombie connections. Try to change the transformer and see if you can replicate the issue.

**Comment by akreienbring** [comment]
I already did tried that. Unfortunatly I'm unable to install websockets (on windows7 for some errors pointing to missing python stuff) and socksjs currently breaks my athorization scheme, as I attach a token to the http query in
```
			primus.on('outgoing::url', function connectionURL(url) {
				url.query = 'token=' + (token || '');
			});
```
(maybe this event is not fired using socksjs...

**Comment by akreienbring** [comment]
Some news on this: When I use the websockets transformer the clients don't get disconnected.
Due to this post https://github.com/websockets/ws/issues/444 one can ignore the installation errors on Windows7 64. 
I'm watching for 15 minutes now and not a trace of any disconnect / reconnect cicles.

BTW: What is the maximum setting for the server timeout setting?

**Comment by lpinca** [comment]
@akreienbring the maximum value you can use in a `setTimeout`, but I would use something reasonable or completely disable it.
