### ISSUE TITLE
Force reconnect

### ISSUE THREAD

**Issue by krzysztofantczak** [primus/primus#280]
Hi,

Is it possible to force reconnection (on the client side) before timeout goes down to zero? If not it would be nice feature.

**Comment by firasd** [comment]
Just an update on this and a suggestion...

It seems like primus.clearTimeout is no longer a valid function, I had to call primus.timers.clear('reconnect');

It would be useful if there was a way to reset the current timeout to 0 seconds instead of having to call primus.open() so that upon "force reconnect" the primus.on('reconnected', ..) event would fire.

**Comment by lpinca** [comment]
@firasd you can probably do
```js
primus.timers.adjust('reconnect', 0);
```
but I haven't tested it.

**Comment by firasd** [comment]
@lpinca unfortunately that doesn't work... in fact I was mistaken: <code>primus.timers.clear('reconnect')</code> does not work; the scheduled reconnect attempt still fires even after the connection is open again.

Should I open a new issue? What would be required for "force reconnect" is a way to:

* Check if a reconnect is scheduled;
  * If so, reset the countdown to 0;
* Otherwise, schedule a reconnect attempt in 0 seconds

**Comment by lpinca** [comment]
I forgot that it's the `recovery` module that handles the reconnection, try this:
```js
primus.recovery.reset().reconnect();
```

**Comment by firasd** [comment]
That seems to work, thanks!

So this is what I've put together

```javascript
      if(primus.recovery.attempt && primus.recovery.attempt.scheduled) {
        primus.recovery.reset().reconnect();
      } else {
        primus.open();
      }
```

**Comment by lpinca** [comment]
You can simplify the check to see if it the reconnection procedure is active:
```js
if (primus.recovery.reconnecting()) {
  primus.recovery.reset().reconnect();
} else {
  primus.open();
}
```

**Comment by firasd** [comment]
Perfect. Thanks!
