### ISSUE TITLE
Force client disconnect

### ISSUE THREAD

**Issue by podviaznikov** [primus/primus#362]
How can I disconnect client from the server (client side)?
Are there any methods I need to call like `destroy`, `close` when I don't want to get events from the server?

I couldn't find anything in the docs.

**Comment by lpinca** [comment]
- **Server-side**

  You can disconnect a client from the server by calling `end()` on the `spark` instance:

  ```js
  primus.on('connection', function (spark) {
    // Use `spark.end(undefined, { reconnect: true });` to trigger a client side reconnection
    spark.end();
  })
  ```

- **Client-side**

  If you need to close the connection from the client side, you can call [`end()`](https://github.com/primus/primus#primusend) on the `primus` instance:

  ```js
  var primus = new Primus(url);

  primus.on('open', function () {
    primus.end();
  });
  ```

  If you want to destroy the `primus` instance, because you no longer need it, you can call [`destroy()`](https://github.com/primus/primus#primusdestroy) on the `primus` instance. This disconnects the client, but also frees all the internal resources:

  ```js
  var primus = new Primus(url);

  primus.on('open', function () {
    primus.destroy();
    // If you want to open a new connection you have to instantiate a new object.
  });
  ```

**Comment by podviaznikov** [comment]
Thank you!
