### ISSUE TITLE
Cannot read `timeout` of undefined caused by WebSocket heartbeat

### ISSUE THREAD

**Issue by STRML** [primus/primus#363]
This is one it looks like I caused via #323, but I wanted to ask a question about it.

The error:

```
TypeError: Cannot read property 'timeout' of undefined
    at Sparky.heartbeat (/srv/www/api/shared/node_modules/primus/spark.js:109:39)
    at WebSocket.emit (events.js:98:17)
    at Receiver.onping (/srv/www/api/shared/node_modules/ws/lib/WebSocket.js:816:10)
    at /srv/www/api/shared/node_modules/ws/lib/Receiver.js:645:14
    at Receiver.flush (/srv/www/api/shared/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.opcodes.9.finish (/srv/www/api/shared/node_modules/ws/lib/Receiver.js:648:12)
    at Receiver.expectHandler (/srv/www/api/shared/node_modules/ws/lib/Receiver.js:630:33)
    at Receiver.add (/srv/www/api/shared/node_modules/ws/lib/Receiver.js:91:24)
    at Socket.firstHandler (/srv/www/api/shared/node_modules/ws/lib/WebSocket.js:775:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
```

It appears that the `primus` property has been removed from the socket, but the underlying transformer is still receiving a `ping` event and calling `spark.heartbeat()`.

I can't see where the `primus` property is removed from `spark`, but I would assume it's on destruction; but in that case, why wouldn't `'close'` have been fired, which [removes all listeners](https://github.com/primus/primus/blob/master/transformers/websockets/server.js#L60)?

**Comment by lpinca** [comment]
@STRML I've received the same error yesterday. I'm still investigating but at the moment I don't have a test case to reproduce the issue.
I think that it's a bug in `ws`.

Here is my stack trace:
```
[04/01 14:25:59 GMT+0200][err]   if ('number' !== typeof spark.primus.timeout) return spark;
[04/01 14:25:59 GMT+0200][err]  
[04/01 14:25:59 GMT+0200][err]      ^
[04/01 14:25:59 GMT+0200][err] TypeError: Cannot read property 'timeout' of undefined
[04/01 14:25:59 GMT+0200][err]     at Sparky.heartbeat (/opt/run/snapshot/package/node_modules/primus/spark.js:109:39)
[04/01 14:25:59 GMT+0200][err]     at WebSocket.emit (events.js:98:17)
[04/01 14:25:59 GMT+0200][err]     at Receiver.onping (/opt/run/snapshot/package/node_modules/ws/lib/WebSocket.js:816:10)
[04/01 14:25:59 GMT+0200][err]     at /opt/run/snapshot/package/node_modules/ws/lib/Receiver.js:645:14
[04/01 14:25:59 GMT+0200][err]     at Receiver.flush (/opt/run/snapshot/package/node_modules/ws/lib/Receiver.js:336:3)
[04/01 14:25:59 GMT+0200][err]     at Receiver.opcodes.9.finish (/opt/run/snapshot/package/node_modules/ws/lib/Receiver.js:648:12)
[04/01 14:25:59 GMT+0200][err]     at Receiver.expectHandler (/opt/run/snapshot/package/node_modules/ws/lib/Receiver.js:630:33)
[04/01 14:25:59 GMT+0200][err]     at Receiver.add (/opt/run/snapshot/package/node_modules/ws/lib/Receiver.js:91:24)
[04/01 14:25:59 GMT+0200][err]     at Socket.firstHandler (/opt/run/snapshot/package/node_modules/ws/lib/WebSocket.js:775:22)
[04/01 14:25:59 GMT+0200][err]     at Socket.emit (events.js:95:17)
[04/01 14:25:59 GMT+0200][err]                  
```

**Comment by lpinca** [comment]
The `primus` property is removed [here](https://github.com/primus/primus/blob/71f6611e9412783e2bfd52f4e5f4d53700bddc2c/spark.js#L268-L279).

**Comment by STRML** [comment]
Okay. So:

1. The socket closes
1. Socket emits `incoming::end` then removes all listeners
1. `incoming::end` [calls spark.end()](https://github.com/primus/primus/blob/71f6611e9412783e2bfd52f4e5f4d53700bddc2c/spark.js#L233)
1. `spark.end()` [fires 'end'](https://github.com/primus/primus/blob/71f6611e9412783e2bfd52f4e5f4d53700bddc2c/spark.js#L521)
1. `'end'` handler removes properties

So how could `heartbeat()` be called by the `'ping'` event, if the listener was removed in step 2?

**Comment by STRML** [comment]
Would an explicit call to `spark.end()` not actually fire the socket `'close'` event?

**Comment by lpinca** [comment]
`spark.end()` fires [`outgoing::end`](https://github.com/primus/primus/blob/71f6611e9412783e2bfd52f4e5f4d53700bddc2c/spark.js#L520) that triggers [`socket.close()`](https://github.com/primus/primus/blob/71f6611e9412783e2bfd52f4e5f4d53700bddc2c/transformers/websockets/server.js#L48), but the [`close`](https://github.com/primus/primus/blob/71f6611e9412783e2bfd52f4e5f4d53700bddc2c/transformers/websockets/server.js#L60-L64) event is emitted **after** the [`end`](https://github.com/primus/primus/blob/71f6611e9412783e2bfd52f4e5f4d53700bddc2c/spark.js#L255-L279) event, so it's possible that a `ping` event is received after the `end` event on the spark.

**Comment by STRML** [comment]
A ping would have to come through before asyncevent managed to fire the close handler that removed listeners, but after that 10 ms setTimeout that removed the `primus` property. Doesn't seem possible.

**Comment by lpinca** [comment]
Here is a test case:
```js
'use strict';

var Client = require('faye-websocket').Client
  , Primus = require('primus')
  , primus
  , server
  , ws;

server = require('http').createServer();
primus = new Primus(server);

primus.on('connection', function (spark) {
  spark.on('end', function () {
    ws.ping('ping');
  });
  spark.end();
});

server.listen(3000, function () {
  ws = new Client('ws://localhost:3000/primus');
});
```
If it doesn't work, try to decrease this [delay](https://github.com/primus/primus/blob/5b0994943ed8e440864fc2a7ab35be2401a1b878/spark.js#L279). Setting it to `8` will make the test 100% reproducible on my early 2009 MacBook Pro, but if you have better hardware you may need to lower this further.

The problem, as expected, is caused by the fact that the WebSocket can still emit `ping` and `message` events after calling [`socket.close()`](https://github.com/primus/primus/blob/5b0994943ed8e440864fc2a7ab35be2401a1b878/transformers/websockets/server.js#L48).
Now `message` events are simply dropped because we destroy the `ultron` instance [here](https://github.com/primus/primus/blob/5b0994943ed8e440864fc2a7ab35be2401a1b878/spark.js#L522) but `ping` events can still call `spark.heartbeat()`.

I'm not sure how to fix this. We have some options:

1. Remove the `ping` listener [here](https://github.com/primus/primus/blob/5b0994943ed8e440864fc2a7ab35be2401a1b878/transformers/websockets/server.js#L48).
2. Add a `readyState` check [here](https://github.com/primus/primus/blob/5b0994943ed8e440864fc2a7ab35be2401a1b878/spark.js#L109):

  ```js
  if (Spark.CLOSED === this.readyState || 'number' !== typeof spark.primus.timeout) return spark;
  ```
3. Tweak our `incoming::ping` listener to only call `heartbeat()` when `time` is missing:
  ```js
  ultron.on('incoming::ping', function ping(time) {
    if (!time) return spark.heartbeat();

    spark.emit('outgoing::pong', time);
    spark._write('primus::pong::'+ time);
  });
  ```
  ```js
  socket.on('ping', spark.emits('incoming::ping', function (next) {
    next(undefined, null);
  }));
  ```

**Note**: The issue is only reproducible with `ws >= 0.6.4` due to this [change](https://github.com/websockets/ws/commit/7325d013df15d0a19e8cf049db11a8fa02039e5a#diff-ac4015dfd17173726807df0406ae1d2bR756).

/cc @3rd-Eden

**Comment by STRML** [comment]
I think the third option is the cleanest, so long as it's commented
properly (it's still a bit messy). I didn't emit `incoming::ping` from
the `ws` ping handler because it would emit an outgoing ping message,
but if it's smart enough to notice no time attached I think it'll work fine.

Is there the potential for a legitimate `primus::ping` message to come
through without a timestamp and thus get confused by this logic change?

**Comment by STRML** [comment]
Great work reproducing this, by the way!

**Comment by lpinca** [comment]
@STRML I also find the third option the cleanest.

> Is there the potential for a legitimate `primus::ping` message to come through without a timestamp and thus get confused by this logic change?

No, the client should always send a timestamp with the [ping message](https://github.com/primus/primus/blob/5b0994943ed8e440864fc2a7ab35be2401a1b878/primus.js#L966). If the timestamp is missing, something is wrong with the client implementation.
To make it a bit more resilient we could explicitly check if it is `undefined`:
```js
ultron.on('incoming::ping', function ping(time) {
  if (time === undefined) return spark.heartbeat();

  spark.emit('outgoing::pong', time);
  spark._write('primus::pong::'+ time);
});
```
In this way we make sure that it is only fired by `ping` events because if the client implementation is wrong and a timestamp is not sent, `time` is an [empty string](https://github.com/primus/primus/blob/5b0994943ed8e440864fc2a7ab35be2401a1b878/spark.js#L388)

There are two things that are blocking me:

1. This implementation will affect all the transformers, but the issue is only in `websockets`, so it might make more sense to address the issue in that transformer and not the `Spark`.
2. Something scary, unrelated to this issue in question, that I realized while investingating: we are dropping all messages that come after `socket.close();` (maybe this is the right thing to do given that we called `spark.end();`).

**Comment by STRML** [comment]
Re #1, other transforms will or at least should be supporting protocol-level ping in the future. I believe some may already.

**Comment by lpinca** [comment]
@STRML that's true.
I was also considering something like this:
```diff
diff --git a/spark.js b/spark.js
index 0998ee4..b349fb4 100644
--- a/spark.js
+++ b/spark.js
@@ -250,12 +250,21 @@ Spark.readable('__initialise', [function initialise() {
   });
 
   //
+  // Default listener for the `outgoing::end` event. It will be replaced
+  // in the transformer.
+  //
+  ultron.on('outgoing::end', spark.emits('end'));
+
+  //
   // End is triggered by both incoming and outgoing events.
   //
   ultron.on('end', function end() {
     clearTimeout(spark.timeout);
     primus.emit('disconnection', spark);
 
+    spark.ultron.destroy();
+    delete spark.ultron;
+
     //
     // We are most likely the first `end` event in the EventEmitter stack which
     // will make our callback the first to be execute. If we instantly delete
@@ -518,9 +527,6 @@ Spark.readable('end', function end(data, options) {
 
   this.readyState = Spark.CLOSED;
   this.emit('outgoing::end');
-  this.emit('end');
-  this.ultron.destroy();
-  delete this.ultron;
 
   return this;
 });
diff --git a/transformers/websockets/server.js b/transformers/websockets/server.js
index c698e59..3883e57 100644
--- a/transformers/websockets/server.js
+++ b/transformers/websockets/server.js
@@ -44,8 +44,13 @@ module.exports = function server() {
         , socket.upgradeReq                       // Reference to the HTTP req.
       );
 
-      spark.on('outgoing::end', function end() {
-        if (socket) socket.close();
+      spark.ultron.remove('outgoing::end').on('outgoing::end', function end() {
+        if (socket) {
+          socket.on('close', spark.emits('end'));
+          return socket.close();
+        }
+
+        spark.emit('end');
       }).on('outgoing::data', function write(data) {
         if (socket.readyState !== socket.OPEN) return;
         if ('string' === typeof data) return socket.send(data, noop);
```
This will make sure that all data is consumed before emitting the `end` event, fixing also this issue.
Of course, if we decide to go with this, we must update the other transformers accordingly.

**Comment by STRML** [comment]
Looks great. Thanks!
