### ISSUE TITLE
WebSocket disconnects after about 60 seconds

### ISSUE THREAD

**Issue by mhamann** [primus/primus#374]
I wrote a websocket server using primus and ws. It seems to work, except that it closes the connection with the client after about 60 seconds. Data flows across the socket without a problem, but even sending data, the socket still closes around 60 seconds after open.

Any clues as to why this is occurring?

**Comment by 3rd-Eden** [comment]
If you wrote a custom server or client, you're probably missing the ping packages that we send to keep the connection alive and open. Could you share some code?

**Comment by mhamann** [comment]
Yep, that was the problem. I implemented the ping protocol and things remained stable.

It seems like this is somewhat proprietary to Primus--or at least this implementation of it. Is there a way to turn it off or make it optional? Or is there a "standard" way of doing the pings instead of `primus::ping::<timestamp>`?

**Comment by 3rd-Eden** [comment]
Well there are good reasons for the ping as it fixes some horrible network and proxy based connectivity issues. The protocol is documented in the readme: https://github.com/primus/primus#protocol 

There is no standard way of doing pings because the W3C team decided that browsers should decide if they want to send pings from client -> server and not give us developers an API for it. That's why we're forced to send these custom packets.

**Comment by lpinca** [comment]
@mhamann yes you can disable the heartbeats setting the `timeout` and the `ping` options to false:
```js
// server instance
var primus = new Primus(server, { timeout: false });

// client instance
var socket = new primus.Socket(url, { ping: false });
```

**Comment by lpinca** [comment]
Closing this, but please post back if you need more help.
