### ISSUE TITLE
'end' event called really late on the server when redirecting or refreshing in the website

### ISSUE THREAD

**Issue by peterwilli** [primus/primus#398]
Hi,

We have found quite a big problem in our setup. Users are redirect from and to pages on the same domain a lot of times and I have found weird disconnects happening at random times while the user was still online!

Turns out, that if you redirect to another page the connection stays open for some reason (although, it looks like that) and the end event is not called until after a few seconds.
Even if I close my browser the server has to take a few seconds to register the 'end' event.

It is important for our program to register the end event as soon as possible (when the user closes his window)

I have a proof-of-concept here: https://mega.nz/#!6ZYFVRyY!pIOlpPjqiHT7I-CRUTOH0stI0fVsecxBIHYD0uMovps

What you have to do is:

 - Unpack zip and call `node main.js`
 - Open localhost:8080 in your browser
 - Watch the page refresh 2 times
 - In the console, you now see that the online counter goes up but not down until after a few seconds
  - If it does, repeat the steps and try again. It will happen.

If all is well you see logs like this:

```
Connection closed online counter: 0
connection made! VUB0c_Ru_NnQLGd3AAAH online counter: 1
connection made! vN3Q5Vm_jXRRPly-AAAI online counter: 2
connection made! XY6-Ylcr2JcUqO3ZAAAJ online counter: 3
Connection closed online counter: 2
connection made! nxeU-ytRRuuP04ksAAAK online counter: 3
Connection closed online counter: 2
Connection closed online counter: 1
```

If anyone can make sense of this, that would be awesome!

**Comment by lpinca** [comment]
I can only reproduce the issue using the `engine.io` transformer.
In this [gist](https://gist.github.com/lpinca/bf2c318d655ea8b75981) I put a test case using only `engine.io`.
If you refresh the page fast enough you get similar results to the ones shown in your report.
I don't have the time to investigate further at the moment, but the issue is in `engine.io` and it should be probably fixed there unless we find a workaround.

In the meantime you can file a bug in the `engine.io` issue tracker and use another transformer.

**Comment by peterwilli** [comment]
@lpinca  I recall we had this in sockjs transfer too (I actually moved to that because I thought it was only in engine.io) but it could be a different bug as well. I'll try to reproduce using a non-engine.io tranformer in the meantime. Until then it's safe to assume it only happens in Engine.io.

It indeed happens when you refresh quickly as well.

**Comment by lpinca** [comment]
I took some time to look into this and unfortunately I think that there is not much we can do about it.
The problem, as I see it, is in the polling transport which is used by Engine.IO as initial transport.

If a redirect or a page refresh occurs right after the socket creation, the server has no way to detect that the socket has disconnect, because a new poll request has not been created yet, and thus it will close it only when the internal timeout of the socket expires.

As proof consider the following [test case](https://gist.github.com/lpinca/bf2c318d655ea8b75981/ac3cfd615739ab8eec28fa2e58b3adf59a8ebc57).

**Comment by SuperSpyTX** [comment]
This explains exactly why during my initial testing with Socket.IO, that the online counter increases when I excessively refresh the page.

Good thing I'm not the only one.

**Comment by twmobius** [comment]
I think the problem with engine.io occurs even when the transport used by engine.io is ws and not long-polling. 

In my setup I tend to see around 2 seconds delay between the refresh and the actual spark.on('end', ...) event being fired. And it happens always, not matter how long I've been in the current page.

**Comment by twmobius** [comment]
Ok update on this. Same thing happens with SockJS. 

I've resolved this by adding client-side forcing the socket to end just before the page unloads:
`
window.addEventListener("beforeunload", function (event) {
  primus.end(); 
});
`
