### ISSUE TITLE
Feature request: Allow multiple URLs to be specified

### ISSUE THREAD

**Issue by scriby** [primus/primus#448]
I have a use case that is probably somewhat rare, but I thought I'd bring it up anyway to see what you think.

My application can connect to one of several possible servers, and it doesn't matter which it gets connected to. Not all the servers will be available to all users all the time, so users will just attempt to connect to servers in the list of servers until a connection is accepted. Some of the servers are only available on specific LANs and it depends on where the user is as to which servers they can connect to.

I've been working on making this work with primus. I coded up the initial server selection piece, then realized that I can't use the builtin reconnect logic either, as it needs to try all servers again instead of just the last one it was connected to.

I'm imagining that primus could accept an array of urls to connect to instead of a single URL to support the use case.  It may be a fringe enough case that it doesn't make sense to support it, but I figured I'd raise it up anyway.

**Comment by 3rd-Eden** [comment]
@scriby I highly doubt that the functionality that you describe will make it way in to the primus core as it seems to really specific to your usecase/architecture. But we'll do our best to help you anyways. We have a `outgoing::url` event on the client which could be used to transform the URL every time we attempt to connect. The only problem here is that the code currently doesn't allow the transformation of the host.

See https://github.com/primus/primus/blob/master/primus.js#L1059-L1125 for the logic

```js
var primus = new Primus(url);

primus.on('outgoing::url', function (options) {
 options.protocol = 'http';
});
```

We could just change this in the next release so it will check for an `options.host` instead of `url.host`. Would that be suffecient for you to implement the functionality that you described above?

**Comment by scriby** [comment]
Thanks for the suggestion!

It seems like connection backoff wouldn't work quite right, since it would be shared across all servers instead of per-server.

I was able to get a pretty clean solution by setting "strategy: '' " to disable automatic reconnection. Then, I just listen for the end event and run through my connection logic again. I implemented a simplified version of random-exponential backoff inspired by primus.

So I am good to go for now. I really appreciate you taking the time to help! I'll go ahead and close the issue for now.

**Comment by lpinca** [comment]
@scriby to correctly disable the reconnection set it to `false`.

**Comment by scriby** [comment]
I initially tried setting `reconnect: false` but that didn't seem to work. Is that correct?

**Comment by lpinca** [comment]
Sorry I have not been clear. The option name is `strategy` and it should be set to `false` to disable reconnection.
