### ISSUE TITLE
using ejson as parser and sending message from client wont parse date

### ISSUE THREAD

**Issue by dotob** [primus/primus#469]
**Version:**
primus@5.2.1
ejson@2.1.2

**Environment:**
  - **Operating system:** MacOs 
  - **Browser:** not applicable
  - **Node.js:** 6.2.0

**Expected result:** [{"extid":"a","d":{"$date":949359600000}}]

**Actual result:** [{"extid":"a","d":{}}]

**Steps to reproduce:**
```javascript
let Primus = require("primus");
var primus = Primus.createServer({ port: 4444, transformer: 'websockets', parser: 'ejson' });
primus.on('connection', (spark) => {
	spark = spark;
	spark.on('data', (msg) => {
		console.log(msg);
		done();
	});
});
var Socket = Primus.createSocket({ transformer: 'websockets', parser: 'ejson' })
var client = new Socket("ws://localhost:4444");
client.write([{extid:"a", d:new Date(2000, 1, 1)}]);
```

I do not understand why the parser does not produce a real ejson string. When i do 
```javascript
var EJSON = require('ejson');
EJSON.stringify([{extid:"a", d:new Date(2000, 1, 1)}]);
```
in the same environment it works like a charm.

**Comment by lpinca** [comment]
Hi, thank you for the report.
We build the client for Node.js using the [`load`](https://github.com/3rd-Eden/load) module. Under the hood `load` uses `vm.runInNewContext`.
The issue happens because the `Date` constructor is not the same in the new context. For example:
```js
const vm = require('vm');

const sandbox = { d: new Date() };
vm.runInNewContext('x = d instanceof Date', sandbox);

console.log(sandbox.x);
```
This creates a [false negative](https://github.com/primus/ejson/blob/f45b358582e8d0a354d9226e413d9b0506e5e3df/vendor/ejson.js#L88) which makes `EJSON.stringify` fails.

To "fix" this we can override the `Date` constructor in the new context adding `Date: Date` [here](https://github.com/primus/primus/blob/b3eee12d267565537f02fe41b4acbb910941e528/index.js#L178) but I'm not sure if it is the best approach as there might be other globals that cause the same issue.

Fortunately the issue is limited to the Node.js client.

**Comment by dotob** [comment]
hi @lpinca,

thanks for the awesome insight. Never would have found this by my self.

I understand that the solution to override the Date ctor is not perfect. But at least it would fulfill the expected behavior of ejsons builtin converters. 

Unfortunately I cannot give more educated help...

Perhaps someone else has a better solution or at least an idea how I could work around this issue as I do need the node client.

**Comment by lpinca** [comment]
One way to fix this would be to use `Object.prototype.toString.call()` instead of the `instanceof` operator in the EJSON lib. It already depends on `underscore` and `underscore` implements `_.is[Type]` using `Object.prototype.toString.call()`, see https://github.com/jashkenas/underscore/blob/3d118cf09fe4d3432aef9b5b6ab43e57ee9af34e/underscore.js#L1295.

We can try to submit a pull request and see if they are ok with the change.

**Comment by lpinca** [comment]
If you need an immediate workaround I would monkey patch the `load` module adding the required globals [here](https://github.com/3rd-Eden/load/blob/96915d7b4de879eb60cc26f64b6bf0b40cf056aa/index.js#L96-L99).

**Comment by 3rd-Eden** [comment]
We could just supply the globals in primus directly to loads.

**Comment by 3rd-Eden** [comment]
Adding the build-in globals like Date to https://github.com/primus/primus/blob/master/index.js#L177-L178 should resolve this issue

**Comment by lpinca** [comment]
Yes, this is the list from what I've gathered:

- `Date`
- `Uint8Array`
- `Array`
- `RegExp`

**Comment by lpinca** [comment]
@3rd-Eden that's what I've suggested in my first comment but I still think it would be nice to fix this in the EJSON lib.

**Comment by lpinca** [comment]
Ok, I'm not even trying to submit the pr. The overhead added by the `Object.prototype.toString.call()` solution is too big. The pr will never be accepted. Let's override the globals 😞.

**Comment by lpinca** [comment]
I will cut a new release tomorrow if there are no objections.

**Comment by dotob** [comment]
you are awesome! thanks guys. 

...
