### ISSUE TITLE
support deepstream.io？

### ISSUE THREAD

**Issue by beeplin** [primus/primus#511]
[https://deepstream.io/blog/deepstream-2.0-more-than-1000-times-faster-than-socket.io/](https://deepstream.io/blog/deepstream-2.0-more-than-1000-times-faster-than-socket.io/) 

deepstream.io is a new realtime framework which reported high performance. Seems very promising.

**Comment by lpinca** [comment]
I'm not sure how deepstream.io works and if it is possible or makes sense to integrate it in Primus.
According to https://deepstream.io/tutorials/guides/what-is-deepstream/ deepstream is a "self hosted Firebase".

I think the two projects serve a different purpose so it's unlikely to happen.

**Comment by 3rd-Eden** [comment]
Deepstream is nothing more than code on top of uws. So instead of supporting that you could just use uws directly in primus

**Comment by lpinca** [comment]
@beeplin I close this. Your question about why uWebSockets doc says "stay away from Primus" has also been answered. My comments have been promptly removed as always but you should have received GitHub notifications.

Please comment or reopen if needed.

**Comment by 3rd-Eden** [comment]
@lpinca Is that non sense still going on? Gotta love it when maintainers to full keyboard warrior and spread bullshit about other projects. 

I like the part where it calls out Primus about:

- **ws by default** We don't have transformers by default: https://github.com/primus/primus/blob/master/package.json#L52-L62
- **run by dictators** I think he mis spelled passioned maintainers. 
- **ignores criticism** No clue what he's referring to here, but like people always need to listen to him
- **refuses anything other than their way** Isn't that the whole reason why people create their own projects? To do a certain thing, their way? 
- **performs/scales as if written by a 3 year old child with crayons up their nose** I take this as compliment when it comes to scaling, you don't want to add complexity to your system. Complex systems are hard to scale, simple system are easy to scale -- so is primus. I wrote a chat server based on primus/ws and postgresql for a major gaming site 2 years ago. It auto scales, handles millions of messages and that while maintaining a 99.9% uptime. (0.1% is from server upgrades) total LoC for the project is `6528` (excluding dependencies)

I think that he is still butt hurt about me refusing to change the description of `ws`.

**Comment by lpinca** [comment]
@3rd-Eden yeah but I honestly don't care anymore.

`uws` is faster and scales better than `ws` that is true and I have no problem updating the description with just "A fast cross platfrom RFC-6455 WebSocket implementation for Node.js" instead of "fastest" but the numbers in `uws` README are wrong as it comprare the C++ `uws` server with `ws` with default settings on (permessage-deflate, client tracking, etc.).

I tried to point that out, it was a heated discussion, and as a result I've been blocked from the uWebSockets project, fine.

When `uws@0.10` was released I privately disclosed a security (DoS) vulnerability. It has been ignored for weeks, so I reported it to nodesecurity.io. I've been called faggot for doing that.

Then Primus was downgraded to "not use", fine, I don't know why but that's acceptable.

Then @beeplin asked why those project where listed as "stay away". Alex answered with his opinions, the ones you posted above. I felt obliged to answer with data proving that Primus was faster than the alternatives (couldn't test deepstream.io). Since I was blocked I created a new user "banned-lpinca" to post that data. As a result I've been reported for violating point 7 of GitHub [terms of services](https://help.github.com/articles/github-terms-of-service/). GitHub suspended both accounts and only after ~24h I was able to get "lpinca" back.

So yeah censorship works but we are the dictators, fine.

I seriously no longer care. I would only keep supporting `uws` because the project is good and because there are a (increasing) number of Primus users that are using it.
