### ISSUE TITLE
Ping information on spark.on('data') event

### ISSUE THREAD

**Issue by twmobius** [primus/primus#608]
**Version: 7.0.1**

**Environment:**
  - **Operating system: Ubuntu 14.04**
  - **Node.js: 8.4.0**

On `spark.on('data', function ... {});` callback on the server I am getting primus::ping::1506003946021 messages. This started after I upgraded to 7.1.0.

Is that normal? Is there a way to get the spark data without those low level information?

**Comment by lpinca** [comment]
No it isn't normal you should only receive those messages in the listeners of the `'incoming::data'` event.

Did you rebuild the client for version 7.1.0?

**Comment by twmobius** [comment]
Yes I did. I don't know however if the old version of the client js is cached on user's browsers.

I could wait a few days and see if it stops popping up in the logs. But in the meantime I am guessing the heartbeat won't work as expected right?

**Comment by lpinca** [comment]
> But in the meantime I am guessing the heartbeat won't work as expected right?

Correct.

Pings are now sent from server to client but you are receiving them on the server. This probably happens because there is an old client still sending pings.

**Comment by lpinca** [comment]
Closing this, feel free to continue discussing on the closed thread.

**Comment by southbite** [comment]
OK, so starting this discussion again :) - we have a bunch of legacy clients, that cannot be upgraded, that are sending ping events. We are now going through the exercise of upgrading primus, but those remote clients are breaking because the server pings are finding their way into their incoming data.

Is there some way we can override outgoing messages on the server side to prevent the server sending pings to old clients? transforms do the job for incoming messages, so we fixed where our server was breaking when it received pings from old clients. But outgoing transforms do not work for modifying system messages, as the _write method is called for primuses protocol messages. 

Any of the smart people who built primus know how we can inject a little piece of middleware that checks for server pings being written to a spark (that we somehow know is an old client - solvable / a problem for later) without us having to fork primus?
