### ISSUE TITLE
Tracking issue: Vulnerable `debug` version in `setheader` dependency

### ISSUE THREAD

**Issue by joepie91** [primus/primus#663]
Not a stand-alone bug report, just a tracking issue for 3rd-Eden/setHeader#2 so that the dependency can be updated here once it's fixed. An update wouldn't happen automatically since `setheader` is currently at a pre-`1.0.0` version.

**Comment by paulocoghi** [comment]
It seems that @3rd-Eden is a little busy to merge https://github.com/3rd-Eden/setHeader/pull/3 and no other user has the permission to do it.

Since security is a real priority, if it takes longer, I will suggest a fork of [3rd-Eden/setHeader](https://github.com/3rd-Eden/setHeader) to solve this.

**Comment by 3rd-Eden** [comment]
> Since security is a real priority

Oh come-on, you've gotta be kidding me, this particular issue has absolutely nothing to do with security. This about satisfying your fake sense of security because of some incompetent automated system is telling that a dependency has a **potential** vulnerability without analyzing if a said project/module execution paths are even touching the vulnerable code. 

In the case of `debug` it's a **DEBUG** utility. Which is **off** by default. Until, you, as a user, admin of the said server, computer is starting the node process with `DEBUG=*` or `DEBUG=setheader` as environment variable. Which is not something you do in production. And even if you did, the usage of debug and the data we would send to it is **NOT** capable of triggering said bug.

**Comment by lpinca** [comment]
Filed a PR to fix compatibility with Node.js 10: https://github.com/3rd-Eden/setHeader/pull/4

**Comment by 3rd-Eden** [comment]
I don't see how my response is concerning. Maintainers should have the responsibility to assess if a given project is indeed vulnerable for the given exploit and should act accordingly to that. In this case, as well as any other security vulnerability that has been reported to me, I go through the effort of completely digging through the report, the exploit, the patches, the execution path, and determine if it can be something that is exploitable in the given project. 

In this particular case, the answer to that is no, it's not something that can be exploited. Even when `DEBUG=*` is set, it is not vulnerable as there is no user input that is passed through the debug statement that can trigger the said exploit. So actual user impact by this is 0. Given these facts, I have given this particular issue less urgency than other reports that have been securely disclosed that do indeed have user impact which is where my attention is.

And while I agree that low severity security issues eventually needed to be patched, the false sense of urgency is not needed here.

**Comment by lpinca** [comment]
@3rd-Eden can you please release a new version of `setheader` that includes https://github.com/3rd-Eden/setHeader/pull/4 when you have time? So we can finally close this.

**Comment by 3rd-Eden** [comment]
@lpinca It's released as 1.0.1 so it should be automatically installed now.

**Comment by lpinca** [comment]
Thank you.
