### ISSUE TITLE
http://primus.io domain for sale (/expired) ?

### ISSUE THREAD

**Issue by rasmuslp** [primus/primus#697]
When I visit http://primus.io I'm greeted with a site that state the domain is for sale, and a number of helpful links for car insurance, credit cards, and Comcast.

**Comment by 3rd-Eden** [comment]
Yes, sorry about that. I've looked at the amount of the traffic that the domain name received and weighted it against the cost of a `.io` domain, unfortunately, the amount of traffic it received was not justifiable for the cost, especially because it was just a redirection to GitHub. 

I've removed the domain reference from the repo. Sorry for the inconvenience.

**Comment by FREEZX** [comment]
@3rd-Eden forgot this one:
https://github.com/primus/primus/blob/master/package.json#L13

**Comment by lpinca** [comment]
@FREEZX thanks, fixed in https://github.com/primus/primus/commit/a42853f4f600190fb2cf68d1c305b88ee81ab90f.

**Comment by FREEZX** [comment]
@lpinca Just accidentally found it's also listed as the website on the primus account:
https://github.com/primus

**Comment by lpinca** [comment]
Ah, I can't fix that one.

**Comment by 3rd-Eden** [comment]
Should be gone now.
